# Generated by Django 3.1.7 on 2021-03-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0019_auto_20210302_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pharm_pic',
            field=models.ImageField(default='pictures/default.png', upload_to='pictures/'),
        ),
    ]
